package app.enums;

public enum NotificationType
{
    PENDING_COUNT_UPDATED,
    NEW_DISH_SUGGESTION,
    NEW_INGREDIENT_REQUEST,
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    SUGGESTION_APPROVED,
    SUGGESTION_REJECTED
}
