
### GET by ID
GET {{url}}/allergens/16
Authorization: Bearer {{authTokenHeadChef}}

### GET ALL
GET {{url}}/allergens
Authorization: Bearer {{authTokenHeadChef}}

### GET by Name
GET {{url}}/allergens/name/Sell
Authorization: Bearer {{authTokenHeadChef}}

### POST create allergen
POST {{url}}/allergens
Content-Type: application/json
Authorization: Bearer {{authTokenHeadChef}}

{
    "nameDA": "Pinjekerner",
    "nameEN": "Pine nuts",
    "descriptionDA": "Pinjekerner og produkter heraf",
    "descriptionEN": "Pine nuts and products thereof",
    "displayNumber": 15
}

### POST seed EU allergens
POST {{url}}/allergens/seed
Content-Type: application/json
Authorization: Bearer {{authTokenHeadChef}}

### PUT update allergen
PUT {{url}}/allergens/15
Content-Type: application/json
Authorization: Bearer {{authTokenHeadChef}}

{
    "nameDA": "Pinjekerner(Updated)",
    "nameEN": "Pine nuts(Updated)",
    "descriptionDA": "Pinje kerner og produkter her af(Updated)",
    "descriptionEN": "Pine nuts and products thereof (updated)",
    "displayNumber": 15
}

### DELETE allergen
DELETE {{url}}/allergens/15
Authorization: Bearer {{authTokenHeadChef}}

###

