@local = http://localhost:7070/api/v1

### GET by ID
GET {{local}}/allergens/15

### GET ALL
GET {{local}}/allergens

### GET by Name
GET {{local}}/allergens/name/Hvidløg

### POST create allergen
POST {{local}}/allergens
Content-Type: application/json

{
"nameDA": "Pinjekerner",
"nameEN": "Pine nuts",
"descriptionDA": "Pinjekerner og produkter heraf",
"descriptionEN": "Pine nuts and products thereof)",
"displayNumber": 15
}

### POST seed EU allergens
POST {{local}}/allergens/seed
Content-Type: application/json

### PUT update allergen
PUT {{local}}/allergens/15
Content-Type: application/json

{
    "nameDA": "Pinjekerner(Updated)",
    "nameEN": "Pine nuts(Updated)",
    "descriptionDA": "Pinje kerner og produkter her af(Updated)",
    "descriptionEN": "Pine nuts and products thereof (updated)",
    "displayNumber": 15
}

### DELETE allergen
DELETE {{local}}/allergens/15

###

