@local = http://localhost:7070/api/v1

### GET by ID
GET {{local}}/users/1

### GET all
GET {{local}}/users/

### POST create user
POST {{local}}/users/

{
"firstName": "Morten",
"lastName": "Jensen",
"password": "Morten123.",
"email": "test@email.dk"
}

###
