
### GET by ID
GET {{url}}/users/4
Authorization: Bearer {{authToken}}

### GET all users
GET {{url}}/users/
Authorization: Bearer {{authToken}}

### POST Register a new User
POST {{url}}/users
Content-Type: application/json

{
    "firstName": "Morten",
    "lastName": "Jensen",
    "password": "Morten123.",
    "email": "morten@email.com"
}

### POST Login to get JWT Token
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "morten@email.com",
    "password": "Morten123."
}

### POST Create Another User
POST {{url}}/users/
Content-Type: application/json

{
    "firstName": "Anna",
    "lastName": "Hansen",
    "email": "anna@email.com",
    "password": "Anna123."
}

### PUT Update User
PUT {{url}}/users/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "firstName": "Morten",
    "lastName": "Jensen Updated",
    "stationId": 1
}


### PATCH Change Email
PATCH {{url}}/users/1/email
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "test@email.com"
}

### PATCH Change Password
PATCH {{url}}/users/1/password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "currentPassword": "Morten123.",
    "newPassword": "NewSecure123."
}

### PATCH Change Role
PATCH {{url}}/users/1/role
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "userRole": "SOUS_CHEF"
}


### PATCH Assign User(Anna) To Station
PATCH {{url}}/users/1/station/3
Authorization: Bearer {{authToken}}

### DELETE Delete User
DELETE {{url}}/users/2
Authorization: Bearer {{authToken}}

###
